apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /j12017escape/health
            port: 9080
          initialDelaySeconds: 20
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: cloudant_password
            valueFrom:
              secretKeyRef:
                name: cloudant
                key: password
          - name: cloudant_username
            value: "1d401729-cf6a-4a6a-9618-723876e1ac81-bluemix"
          - name: cloudant_url
            value: "https://1d401729-cf6a-4a6a-9618-723876e1ac81-bluemix.cloudant.com"
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
